# Generated by Django 5.2.1 on 2025-05-13 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourstatus',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('published', 'Published')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tourstatus',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='TourPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=50)),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('duration_days', models.IntegerField(editable=False)),
                ('duration_text', models.CharField(editable=False, max_length=50)),
                ('image', models.ImageField(upload_to='package_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapp.tourstatus')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourapp.vendor')),
            ],
        ),
        migrations.DeleteModel(
            name='Packages',
        ),
    ]
