# Generated by Django 5.2.1 on 2025-05-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0002_alter_tourstatus_status_alter_tourstatus_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourstatus',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
