# Generated by Django 5.2.1 on 2025-05-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0003_alter_tourstatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourstatus',
            name='status',
        ),
    ]
