# Generated by Django 5.2.1 on 2025-05-14 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0004_remove_tourstatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='owner_name',
        ),
    ]
