# Generated by Django 5.2.1 on 2025-05-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0006_rename_title_tourstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackages',
            name='description',
            field=models.TextField(max_length=800),
        ),
    ]
