# Generated by Django 5.2.1 on 2025-05-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0007_alter_tourpackages_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackages',
            name='description',
            field=models.TextField(default='', help_text='Enter a detailed description of the package', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tourstatus',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending approval', 'Pending Approval'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='submitted', max_length=100),
        ),
    ]
