# Generated by Django 5.2.1 on 2025-05-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0008_alter_tourpackages_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackages',
            name='expiry_date',
            field=models.DateField(blank=True),
        ),
    ]
