# Generated by Django 5.2.1 on 2025-05-16 15:14

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0009_alter_tourpackages_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='company_name',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0000000', max_length=128, region='IN'),
        ),
        migrations.AlterField(
            model_name='tourpackages',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
