# Generated by Django 5.2.1 on 2025-05-17 14:41

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0010_vendor_address_vendor_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0000000', max_length=128, region='IN', unique=True),
        ),
        migrations.AlterField(
            model_name='tourpackages',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tourstatus',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending approval', 'Pending Approval'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='submitted', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='company_name',
            field=models.CharField(default='Not Provided', max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='tourpackages',
            unique_together={('vendor', 'title')},
        ),
    ]
