# Generated by Django 5.2.1 on 2025-05-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0011_remove_vendor_phone_number_vendor_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='contact_number',
        ),
    ]
