# Generated by Django 5.2.1 on 2025-05-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0012_remove_vendor_address_remove_vendor_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackages',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
