# Generated by Django 5.2.1 on 2025-05-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0013_alter_tourpackages_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackages',
            name='price',
            field=models.CharField(max_length=500),
        ),
    ]
