# Generated by Django 5.2.1 on 2025-05-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0014_alter_tourpackages_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackages',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
