# Generated by Django 5.2.1 on 2025-05-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0017_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='number_of_people',
            new_name='no_of_people',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='status',
            new_name='payment_status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.TextField(default='new'),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default='00', max_length=15),
        ),
    ]
