# Generated by Django 5.2.1 on 2025-05-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0018_rename_number_of_people_booking_no_of_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.TextField(default='please fill'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default='please provide', max_length=15),
        ),
    ]
