# Generated by Django 5.2.1 on 2025-05-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0019_alter_booking_address_alter_booking_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default='please provide', max_length=15, unique=True),
        ),
    ]
